### VALUES YOU SHOULD CHANGE ###

# GENERAL SITE SETTINGS
# title: This will be displayed as the website's name in your browser tab.
title: Discreet Log Contracts
# description: This will be meta HTML tag content. This can be ignored.
description: Smart Contracts for Bitcoin with better privacy and scalability
# baseurl: The subpath of your site
# > set this to "", if you renamed the repository to <user>.github.io
baseurl: "/dlctemp"

# LANDING PAGE
# username: This will displayed on the landing page as your name.
username: Discreet Log Contracts
# typing_text: This will be typed before 'scroll down for more'.
# > set this to your job title, e.g. Fullstack Developer
typing_text: Jekyll Theme
# email: Your E-Mail address for the email button.
email: info@dlc.dev
# For every social button you want to display, set your username or userid
# If you do not use one of the following websites, then leave it empty
# > twitter_username:
github_username: discreetlogcontracts
twitter_username: Suredbits


### END OF VALUES YOU SHOULD CHANGE ###

plugins:
  - "jekyll-github-metadata"

exclude:
  [
    "_assets",
    "Gemfile",
    "Gemfile.lock",
    "gulpfile.js",
    "node_modules",
    "package.json",
  ]
